openapi: 3.0.4
info:
    title: Tiktok-Clone-2025 - OpenAPI 1.0 (Users Module)
    description: User management endpoints for Tiktok Clone API
    version: 1.0.0

servers:
    - url: http://localhost:3000/api
      description: Local Development Server
    - url: https://api.tiktok-clone-2025.io/api
      description: Production Server

paths:
    /users/me:
        get:
            summary: Lấy thông tin người dùng hiện tại
            description: Lấy thông tin chi tiết của người dùng đã đăng nhập.
            operationId: getCurrentUser
            tags:
                - users
            security:
                - bearerAuth: []
            responses:
                '200':
                    description: Lấy thông tin người dùng thành công
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: 'Lấy thông tin người dùng thành công'
                                    data:
                                        $ref: '#/components/schemas/User'
                '401':
                    description: Không có quyền truy cập
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedResponse'
        patch:
            summary: Cập nhật thông tin người dùng
            description: Cập nhật thông tin cá nhân của người dùng đã đăng nhập.
            operationId: updateCurrentUser
            tags:
                - users
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateUserRequest'
            responses:
                '200':
                    description: Cập nhật thông tin thành công
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: 'Cập nhật thông tin thành công'
                                    data:
                                        $ref: '#/components/schemas/User'
                '400':
                    description: Lỗi xử lý
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: Không có quyền truy cập
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedResponse'

    /users/{username}:
        get:
            summary: Lấy thông tin người dùng theo username
            description: Lấy thông tin công khai của người dùng theo username.
            operationId: getUserByUsername
            tags:
                - users
            parameters:
                - in: path
                  name: username
                  required: true
                  schema:
                      type: string
                  description: Username của người dùng
            responses:
                '200':
                    description: Lấy thông tin người dùng thành công
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: 'Lấy thông tin người dùng thành công'
                                    data:
                                        $ref: '#/components/schemas/User'
                '404':
                    description: Không tìm thấy người dùng
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /users/follow:
        post:
            summary: Theo dõi người dùng
            description: Theo dõi một người dùng khác.
            operationId: followUser
            tags:
                - users
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowRequest'
            responses:
                '200':
                    description: Theo dõi thành công
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                '400':
                    description: Lỗi xử lý
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: Không có quyền truy cập
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedResponse'

    /users/follow/{user_id}:
        delete:
            summary: Hủy theo dõi người dùng
            description: Hủy theo dõi một người dùng.
            operationId: unfollowUser
            tags:
                - users
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: user_id
                  required: true
                  schema:
                      type: string
                      format: mongoid
                  description: ID của người dùng cần hủy theo dõi
            responses:
                '200':
                    description: Hủy theo dõi thành công
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                '400':
                    description: Lỗi xử lý
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: Không có quyền truy cập
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedResponse'

    /users/change-password:
        put:
            summary: Đổi mật khẩu
            description: Đổi mật khẩu của người dùng hiện tại.
            operationId: changePassword
            tags:
                - users
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ChangePasswordRequest'
            responses:
                '200':
                    description: Đổi mật khẩu thành công
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
                '400':
                    description: Lỗi xử lý
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: Không có quyền truy cập
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedResponse'

components:
    schemas:
        User:
            type: object
            properties:
                _id:
                    type: string
                    format: mongoid
                    example: '687dfe7e5db6fa0f4b96a5df'
                name:
                    type: string
                    example: 'Nguyen Van A'
                email:
                    type: string
                    format: email
                    example: 'ndtrg281@gmail.com'
                date_of_birth:
                    type: string
                    format: date-time
                    description: Ngày sinh theo chuẩn ISO 8601
                    example: '2025-02-03T06:49:06.375Z'
                updated_at:
                    type: string
                    format: date-time
                    description: Thời gian cập nhật theo chuẩn ISO 8601
                    example: '2025-07-27T03:48:10.405Z'
                created_at:
                    type: string
                    format: date-time
                    description: Thời gian tạo theo chuẩn ISO 8601
                    example: '2025-07-21T08:46:54.495Z'
                verify:
                    $ref: '#/components/schemas/UserVerifyStatus'
                bio:
                    type: string
                    example: 'Hello, I am a TikTok user!'
                location:
                    type: string
                    example: 'Ho Chi Minh City, Vietnam'
                website:
                    type: string
                    format: uri
                    example: 'https://example.com'
                username:
                    type: string
                    example: 'User61448881'
                avatar:
                    type: string
                    format: uri
                    example: 'https://example.com/avatar.jpg'
                cover_photo:
                    type: string
                    format: uri
                    example: 'https://example.com/cover.jpg'
                following_count:
                    type: integer
                    minimum: 0
                    example: 0
                followers_count:
                    type: integer
                    minimum: 0
                    example: 1
                is_followed:
                    type: boolean
                    example: false
                isOwner:
                    type: boolean
                    example: true
            required:
                - _id
                - name
                - email
                - date_of_birth
                - updated_at
                - created_at
                - verify
                - username

        UpdateUserRequest:
            type: object
            properties:
                name:
                    type: string
                    minLength: 1
                    maxLength: 100
                    example: 'Nguyen Van A Updated'
                bio:
                    type: string
                    maxLength: 500
                    example: 'Updated bio'
                location:
                    type: string
                    maxLength: 100
                    example: 'Ho Chi Minh City, Vietnam'
                website:
                    type: string
                    format: uri
                    example: 'https://example.com'
                avatar:
                    type: string
                    format: uri
                    example: 'https://example.com/avatar.jpg'
                cover_photo:
                    type: string
                    format: uri
                    example: 'https://example.com/cover.jpg'

        FollowRequest:
            type: object
            properties:
                user_id:
                    type: string
                    format: mongoid
                    example: '687dfe7e5db6fa0f4b96a5df'
            required:
                - user_id

        ChangePasswordRequest:
            type: object
            properties:
                current_password:
                    type: string
                    minLength: 6
                    example: 'currentpassword'
                password:
                    type: string
                    minLength: 6
                    example: 'newpassword'
                confirm_password:
                    type: string
                    minLength: 6
                    example: 'newpassword'
            required:
                - current_password
                - password
                - confirm_password

        UserVerifyStatus:
            type: number
            description: Trạng thái xác minh người dùng
            enum: [UNVERIFIED, VERIFIED, BANNED]
            example: 1

        SuccessResponse:
            type: object
            properties:
                message:
                    type: string
                    example: 'Thao tác thành công'
            required:
                - message

        ErrorResponse:
            type: object
            properties:
                message:
                    type: string
                    example: 'Bad Request'
                errors:
                    type: object
                    additionalProperties: true
            required:
                - message

        UnauthorizedResponse:
            type: object
            properties:
                message:
                    type: string
                    example: 'Unauthorized'
            required:
                - message
